### ISSUE TITLE
Reconciler: Show more AND less information about each person

### ISSUE THREAD

**Issue by zarino** [everypolitician/everypolitician#204]
Because, in most cases, you just want to do a straight comparison between the incoming person and the potential existing matches, we should limit what we show by default:

The incoming person should only show details that are present on at least one existing person. And each existing person should only show details that are also present on the incoming person.

(Where "details" are things like "Gender: male", or "Date of birth…")

Then, add a little link somewhere (javascript only, with e.preventDefault and e.stopPropagation?) that unfolds all the _extra_ details for the given person, just in case you want to check in more detail.

While you're doing this, also make sure that UUID is listed as one of the extra details for the existing people.

**Comment by tmtmtmtm** [comment]
I've only just realised that in closing #202 in favour of this, we lost one of the things that I think is most important — being able to see at a glance which fields differ.

i.e. if the date of birth on 2 of the 3 cards are different, and one is the same, it should be really easy to see that at a glance, rather than having to scan every row of every card and compare it with the existing data row. If implemented in even quite a basic manner this would probably reduce the reconciliation time by an order of magnitude in many cases.

**Comment by zarino** [comment]
@tmtmtmtm New ticket: #234

**Comment by tmtmtmtm** [comment]
This is now complete.
