### ISSUE TITLE
Reconciler: progress bar is inaccurate

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#205]
When reconciling Slovenia from the current baseline, the progress bar never reaches 100%. By the time it reaches the end, it's only about a quarter of the way across:

![screen shot 2015-11-10 at 20 05 57](https://cloud.githubusercontent.com/assets/57483/11074324/e03a0936-87e6-11e5-8e4e-63c84042d676.png)

**Comment by chrismytton** [comment]
Additionally the screenshot reveals another bug where "old style" reconciliation files are being read in as new style ones causing the output CSV to be incorrect.

Broken out into https://github.com/everypolitician/everypolitician/issues/209

**Comment by chrismytton** [comment]
The progress bars ends up in this state when some of the records are skipped, because we currently [do nothing when skip is selected](https://github.com/everypolitician/everypolitician-data/blob/c3659312bd9f13dbff8d77be7f96a2d821ac0358/templates/reconciliation.js#L23) but then [calculate progress based on how many votes there have been](https://github.com/everypolitician/everypolitician-data/blob/c3659312bd9f13dbff8d77be7f96a2d821ac0358/templates/reconciliation.js#L41).
