### ISSUE TITLE
Canadian Data for the Oxfam App

### ISSUE THREAD

**Issue by paullenz** [everypolitician/everypolitician#226]
Added data to EveryPolitician (and, if required, Global MapIt) so that the Oxfam app can work for Canada as it does Australia and the UK.

Email address data - http://www.parl.gc.ca/parliamentarians/en/members

Boundary data - if we don't have it - https://represent.opennorth.ca

Facebook / Twitter - http://politwitter.ca/page/canadian-politics-twitters/mp/house looks like it could be useful - unsure how up to date it is

**Comment by dracos** [comment]
https://represent.opennorth.ca/data/ also has emails, twitter, in CSV already. It also notes at https://represent.opennorth.ca/api/ that postcodes are not good to work with, just points and sounds like worse than the UK.

**Comment by paullenz** [comment]
Ask for address and geocode?

**Comment by tmtmtmtm** [comment]
The EP Canadian data is [now](https://github.com/everypolitician/everypolitician-data/pull/1488) updated with the latest Represent data (direct from their scraper rather than the above link, so it's possible we're missing some post-processing they do in-between).

We now have 321 of the upcoming members with email addresses, and 17 without, and are re-fetching daily.
