### ISSUE TITLE
countries.json: Provide full URLs for data

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#244]
In `countries.json` we currently provide lots of individual pieces from which a consuming app can determine where to find all the data they might want. 

If we provided full URLs, it would make this simpler in most cases, and would also enable slightly more flexibility in changing things later (e.g. if we were to move away from having everything in a single `everypolitician-data` github repo)

**Comment by tmtmtmtm** [comment]
We'd need to maintain the existing fields (at least for a while), so this would involve adding new ones. Perhaps something like:

Current:

``` json
  {
    "name": "Algeria",
    "country": "Algeria",
    "code": "DZ",
    "slug": "Algeria",
    "legislatures": [
      {
        "name": "People's National Assembly",
        "slug": "Majlis",
        "sources_directory": "data/Algeria/Majlis/sources",
        "popolo": "data/Algeria/Majlis/ep-popolo-v1.0.json",
        "names": "data/Algeria/Majlis/names.csv",
        "lastmod": "1448466499",
        "person_count": 478,
        "sha": "8a94d0b",
        "legislative_periods": [
          {
            "id": "term/7",
            "name": "7th National Assembly",
            "start_date": "2012",
            "slug": "7",
            "csv": "data/Algeria/Majlis/term-7.csv"
          }
        ]
      }
    ]
  }
```

Suggested:

``` json
  {
    "name": "Algeria",
    "country": "Algeria",
    "code": "DZ",
    "slug": "Algeria",
    "legislatures": [
      {
        "name": "People's National Assembly",
        "slug": "Majlis",
        "sources_directory": "data/Algeria/Majlis/sources",
        "popolo": "data/Algeria/Majlis/ep-popolo-v1.0.json",
        "popolo_url": "https://cdn.rawgit.com/everypolitician/everypolitician-data/8a94d0b/data/Algeria/Majlis/ep-popolo-v1.0.json",
        "names": "data/Algeria/Majlis/names.csv",
        "names_url": "https://cdn.rawgit.com/everypolitician/everypolitician-data/8a94d0b/data/Algeria/Majlis/names.csv",
        "lastmod": "1448466499",
        "person_count": 478,
        "sha": "8a94d0b",
        "legislative_periods": [
          {
            "id": "term/7",
            "name": "7th National Assembly",
            "start_date": "2012",
            "slug": "7",
            "csv": "data/Algeria/Majlis/term-7.csv",
            "csv_url": "https://cdn.rawgit.com/everypolitician/everypolitician-data/8a94d0b/data/Algeria/Majlis/term-7.csv"
          }
        ]
      }
    ]
  }
```

Or, rather than appending "_html" to some fields, we could perhaps have a nested hash of URLs:

```
      {
        "name": "People's National Assembly",
        "slug": "Majlis",
        "sources_directory": "data/Algeria/Majlis/sources",
        "popolo": "data/Algeria/Majlis/ep-popolo-v1.0.json",
        "names": "data/Algeria/Majlis/names.csv",
        "sources": { 
            "popolo": "https://cdn.rawgit.com/everypolitician/everypolitician-data/8a94d0b/data/Algeria/Majlis/ep-popolo-v1.0.json",  
            "names": "https://cdn.rawgit.com/everypolitician/everypolitician-data/8a94d0b/data/Algeria/Majlis/names.csv",
        }
        …
```

(perhaps with a different name than `sources`)

@chrismytton any thoughts?

**Comment by davewhiteland** [comment]
I don't understand how this facilitates moving _away_ from a single URL -- for example if EP was to be mirrored and/or aliased (todospolitcos.org?) the problem here is surely there's more than one destination URL, which this doesn't quite address, and the current path information seems to work for those cases because it is (nerdily, if inconveniently) being totally general.

But in general, the `thing_url` containing the constructed URL for `thing` seems like a kind thing to do for humans who otherwise have to build that URL, and means anyone who's looking in countries.json is only one click away from seeing the real data -- which is great for people speculatively investigating EP.

Definitely don't use `sources` though because that term is becoming overloaded. (Maybe could do worse than `urls`?).

**Comment by chrismytton** [comment]
@davewhiteland This change is more to enable us to move to store the data across multiple _repositories_, e.g. have each country in a separate GitHub repository. It's also worth noting that none of the urls would point to everypolitician.org, they're all GitHub/RawGit urls. So adding todospolitcos.org, for example, wouldn't affect the urls in `countries.json`.

@tmtmtmtm Regarding where we put the urls, I generally turn to GitHub to see how they've done things, but in this case they seem to have done it in _at least_ three different ways:
- Using a top level `*_url` property - this seems to be the most common in their API responses, and it the one [documented in the "Hypermedia" section of the API Overview](https://developer.github.com/v3/#hypermedia).
- A [`_links` hash of key/value urls](https://developer.github.com/v3/repos/contents/#response-if-content-is-a-submodule) - this seems to be done as well as `*_url` when there are links which refer to alternative representations of a resource (I think this comes from [Hypertext Application Language](http://stateless.co/hal_specification.html)
- A [`_links` hash of more complex key/value objects](https://developer.github.com/v3/pulls/comments/#response) - this is just a variation on the previous point where the values are hashes rather than strings.

So there's no clear winner. If GitHub is anything to go by then it seems the way to go is to have top level links for everything where relevant, then duplicate those links into a `_links` hash if they refer to alternative representations.
