### ISSUE TITLE
Adding % Coverage onto the individual legislature pages to show what is available on the CSV

### ISSUE THREAD

**Issue by paullenz** [everypolitician/everypolitician#279]
On e.g. 

![screenshot 2016-01-14 12 31 21](https://cloud.githubusercontent.com/assets/909811/12324496/caae5336-baba-11e5-8a48-bd3c1c635446.png)

Having something like:  
![screenshot 2016-01-14 12 37 11](https://cloud.githubusercontent.com/assets/909811/12324594/a73348d4-babb-11e5-8f6d-1f653e49281a.png)

But done better than that, obviously

**Comment by tmtmtmtm** [comment]
Interesting idea. 

There's a slight cross-over with https://github.com/everypolitician/viewer-sinatra/issues/945 and https://github.com/everypolitician/viewer-sinatra/issues/412

**Comment by davewhiteland** [comment]
Javascript-driven (this is a static site, after all) visualisation _diagramming_ the coverage would be my preferred solution to this :-)

The underlying issue @paullenz is exposing is that the displayed (web page) data, in columns, is far from representative of what's in the data; we (EveryPolitician) knows that but can't simply dump it all on the page for very good reasons (TL;DR: too many columns!) but also because on a legislature-by-legislature term-by-term basis we have very patchy coverage so even detecting the "most useful" columns to show is going to be hit-and-miss.

**Comment by paullenz** [comment]
A diagram would be potentially nice, but having the coverage in numbers
that can be read in a second would add real value IMHO

**Comment by tmtmtmtm** [comment]
@davewhiteland — can you give a rough idea of what you mean by diagramming the coverage?

I think @paullenz's idea is interesting because it reveals two slightly different things. One is showing that there _are_ other columns (which there are a variety of possible ways to solve), but the other is that it's also showing at a glance how _complete_ those are, which none of the other suggestions we've had so far do. This would be very useful if you wanted to know how well you could base a WriteInPublic or Politwoops, or whatever, off the data, or how much other digging you'd need to do, or get us to do, first.

**Comment by tmtmtmtm** [comment]
@davewhiteland just because it's a static site doesn't mean we can't pre-generate non-JS visualisations

**Comment by davewhiteland** [comment]
@tmtmtmtm yup I think it's these two things together: if we're showing that the data for this page contains: 40% of people in this repo have email addresses, 20% have twitter handles, 5% gender -- then a little stack of those as a diagram could be prettily displaying that.

And sure, with the non-JS but the point about the JS is... it's an example of a visualisation consuming EP data (presumably without preprocessing it, which is also possible and thence static, sure).

Happy to suggest we do all of the above :-)

**Comment by paullenz** [comment]
+1 I was thinking - e.g. if Oxfam were wondering which countries we could
easily add to the App (ignoring the boundary and geocoding questions for a
moment) they could immediately which countries we have good email coverage
for and which are poor and would require more work before being viable - a
use case that would totally apply to other people thinking of doing a
Politwhoops or WiP or indeed some totally new thing we haven't thought of

**Comment by tmtmtmtm** [comment]
Yep — the idea of a data scorecard appeals to me, where we list how complete our data is for all sorts of fields (and with some indication of people can help us get better info where we're missing things). How and where we display that is the key question.

**Comment by davewhiteland** [comment]
@tmtmtmtm also when you say "This would be very useful if you wanted to know how well you could base a WriteInPublic or Politwoops, or whatever, off the data, or how much other digging you'd need to do, or get us to do, first." then I think you're saying there's a case for us running (separately) an app that does this analysis for us anyway, visualisation or no; perhaps the coverage % it spits out would be something that could be useful (I am comparing this with the https://github.com/everypolitician/everypolitician-names one, which consumes the EP data and exposes its results usefully). If we did that, then that's the data source we could use to diagram/show on the EP website, rather than doing on-the-fly analysis, perhaps?).  Very ouroborusy ;-)

**Comment by tmtmtmtm** [comment]
Yes — it would largely be an extension of that script, as I think reporting on how many of the people (and parties, terms, etc) are cross-linked to Wikidata is also a useful part of the general scorecard approach. 

The main thing we might want to differently from that, though, which I think @paullenz is getting at above, is that _this_ report is likely be most useful simply against the current term, rather than against the legislature as a whole. Knowing that we have 98% of the email addresses for _current_ MPs for a country is a rather different thing than knowing we have 7% of the email addresses for any MP ever for that country…

**Comment by davewhiteland** [comment]
@tmtmtmtm agreed; data for current term is always likely to be especially important, because the current term is the one immediately affecting real people's lives

**Comment by tmtmtmtm** [comment]
I've added a simple script to let us at least be able to look this information up easily. We still need to decide what to actually expose on the site.

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/viewer-sinatra/pull/4254
