### ISSUE TITLE
Communicate better what information we have a Person or a Legislature/Term

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#289]
Currently, when you look at a page like http://everypolitician.org/uk/commons/term-table/56.html it's far from obvious that the underlying data has 
- DOB: 649 (99.8%)
- Gender: 649 (99.8%)
- Email: 648 (99.7%)
- Image: 637 (98.0%)
- Wikidata: 649 (99.8%)
- Twitter: 583 (89.7%)
- Facebook: 234 (36.0%)
  etc

We probably don't (yet) want to get into having a page for every person across the whole site (as for many countries we _don't_ have any of this info, and the page will be almost entirely bare), but we should find a good way of showing some of this, or at least reporting on what we do have.

See also:
- https://github.com/everypolitician/everypolitician/issues/279
- https://github.com/everypolitician/viewer-sinatra/issues/945
- https://github.com/everypolitician/viewer-sinatra/issues/412

**Comment by tmtmtmtm** [comment]
One option might be a little ▶ expander beside each person we _do_ have more data for, that slides out a bunch of extra information about them.

**Comment by zarino** [comment]
We should be careful about not bloating the page too much – eg, if we automatically display an image for each person, suddenly that'll mean, in the UK, 670 images being downloaded at pageload.

**Comment by zarino** [comment]
Revisiting this, I have a question:

Is this about providing a **browseable interface**, for people to see **each piece of information related to each person**, in their web browser?

Or is this about showing the **"completeness" of the dataset** – maybe to give people an idea of what **extra fields are available in the CSV/JSON download**, or maybe also to gently suggest **which bits of the dataset need volunteer improvement**?

---

The former lends itself naturally to either some sort of spreadsheet-like interface (aaargh!) or a drill-down when you interrogate a person at a time.

The latter lends itself to a summary box, or some meta information, about the dataset as a whole, perhaps visualising the dataset's completeness with graphs and pie charts, etc.

**Comment by tmtmtmtm** [comment]
Somewhere in-between. It's definitely _not_ about seeing everything about everyone — we should be directing people to the data for that. (And even if we _did_ want to show it, it doesn't really lend itself to a spreadsheet format, as there would be hundreds of columns, most of which would be empty for most people) 

But we probably should show at least little more about individual people, for at least some of the fields — e.g. if we have 90% of twitter handles that seems like something we should be showing for each person.

But I don't think we'd really want to include date of birth, for example. That sort of thing doesn't seem to add enough value.

**Comment by zarino** [comment]
> But we probably should show at least little more about individual people

Why?

> But I don't think we'd really want to include date of birth, for example.

How do we define which fields add value and which don't? If we start deciding "this is important enough to show in the table, but this isn't", will we be putting ourselves into a sort of gatekeeper role we really don't need to occupy?

**Comment by tmtmtmtm** [comment]
The website needs to walk the tightrope between at least minimally useful and falling into the uncanny valley of looking like a really bad PMO. We _could_ just take the position that we're going to not show anything about people at all — just lots of meta-information about what data we have, but that feels like it's missing a trick, both in terms of simply losing a lot of potential google juice, and also in terms of being accessible to people (especially less technical people who might want to be able to evaluate the data before getting someone else to work out how to actually use it, and for whom descending into raw JSON isn't going to be particularly helpful). 

Even if all we did was add twitter and facebook links beside any politician for whom we know them, I think it would make the site significantly better, both in terms of showing that we _have_ things like this available in bulk, but also when someone is looking for them more as a one-off thing. But this is a chance to rethink whether there's something different we should be doing instead of just slowly expanding the number of fields we show in a table. 

It also feels like we're much more likely to be able to become the standard answer to questions like "Where do I find the twitter handle for a politician?", than "Where do I find the date of birth of a politician?" (which is more likely to be Wikipedia). Though we _should_ be the standard answer to the subtly different question of "Where do I find the dates of birth of _all_ Country X's MPs?"

[This is a little disjointed and hard to articulate, I'm afraid. Happy to also jump on a hangout and throw some ideas around]

**Comment by zarino** [comment]
> Even if all we did was add twitter and facebook links beside any politician for whom we know them, I think it would make the site significantly better

If that’s what you want, it’s dead easy!

![screen shot 2016-01-22 at 15 14 59](https://cloud.githubusercontent.com/assets/739624/12514371/f8d05406-c11a-11e5-96a6-6e92a3c9ac0e.png)

To me, the point at which we start saying "We should present all these various pieces of information about each politician" is the point at which I would probably give them a page each. Otherwise we're just working out more and more complicated ways of toggling bits of one huge page.

**Comment by tmtmtmtm** [comment]
> If that’s what you want, it’s dead easy!

Well, yes, of course. But that's why I've been saying that the point here is to raise the bigger question of what else we could or should do as well or instead of that…

**Comment by zarino** [comment]
So I've submitted a PR for the simplest possible fix, which is just adding a few more bits of information to the table: #2973.

But if we want to show more information than this over time, appending columns to the table won’t be a sustainable strategy. Instead, if that's the goal—but we still don't want each person to have their own profile page—I'd probably lay the people out in their own holding elements, like so:

![screen shot 2016-01-25 at 12 35 47](https://cloud.githubusercontent.com/assets/739624/12551162/618f005e-c360-11e5-81e8-31a2a9f8a97b.png)

No longer confined by horizontal space, the additional fields can be listed vertically below the person's name and political information. And you could make the cards interactive, eg: the "More data" link that unfolds extra fields in place.

We should probably lazy-load the images, so they're only downloaded as the user scrolls down the page. The [Estonian parliament](http://www.riigikogu.ee/riigikogu/koosseis/riigikogu-liikmed/), of all places, has a good working example of this.

Two advantages that we lose by moving away from the table layout are an intuitive sorting mechanism (we'd have to add our own "Sort by: [name/party/area]" dropdown somewhere) and row-spanning for people will multiple memberships (we'd have to just include the multiple memberships inside each person's card).

I've pushed this prototype to [viewer-sinatra branch `289-term-cards-concept`](https://github.com/everypolitician/viewer-sinatra/tree/289-term-cards-concept)

**Comment by davewhiteland** [comment]
Y'know, I think the control-the-sort-order issue is not an important one; the primary purpose of the page is really to show the nature of what EveryPolitician has for this dataset; helping someone get specific data on a particular individual is not so important. So I think this works nicely.

**Comment by tmtmtmtm** [comment]
@zarino I think the 'cards' approach works well. I think it'd be useful to be able to filter those down, rather than to sort, per se — I've added a super-simple JS-based input box to the [`289-term-cards-concept` branch](https://github.com/everypolitician/viewer-sinatra/tree/289-term-cards-concept) to remove non-matching cards as you type, as a proof of concept (feel free to work more magic on it, or suggest an entirely different approach).

Other than that I think the key things we'd need to do here are:
- [ ] Don't hotlink the images (we can probably use the same proxy approach as GenderBalance for this)
- [ ] Make the images look better (they're squished quite nastily atm)
- [ ] Progressive loading
- [ ] Decide which fields to show by default
- [ ] Decide which fields to show in the 'more' section
- [ ] _what else…?_

**Comment by zarino** [comment]
@tmtmtmtm I've pushed some more tweaks to the prototype [`289-term-cards-concept` branch](https://github.com/everypolitician/viewer-sinatra/tree/289-term-cards-concept)

![screen shot 2016-02-03 at 16 15 35](https://cloud.githubusercontent.com/assets/739624/12788493/98b94458-ca91-11e5-8144-a8cbcbbec5df.png)

Most noticeable thing is a "How complete is this dataset" section. Way back at the start of this ticket, I felt like _this_ was what would be useful to a person like _me_ when I'm trying to work out how suitable the dataset is for me to use/reuse. I think the wording definitely needs improving, and there might actually be space there to have a call to action for how someone can help contribute more data.

I've also tidied up the cards somewhat. The fields associated with a person are now spelled out (rather than using icons) and are put on a muted background to keep the primary information (name, photo, political details) relatively easy to scan. I dropped the "More" link and the unfolding thing because, from what I can tell, the only thing that would be in there is Gender, and if we really dislike Gender being visible by default, we may as well just remove it entirely and only show Gender as one of the pie chart summaries at the top. The filtering is also a bit faster now.

Things that don’t work:
- The pie charts don't use real data
- The images are all loaded in one go, rather than being brought in as you scroll.

Other things I noticed:
- Really large parliaments (eg: UK) are a strain on the browser. I'm on a relatively fast device, and as I scroll, I can see Chrome repainting rectangles at the bottom of the screen, trying to keep up. I wonder whether we should consider either paginating the list of people, or loading them in batches as you scroll (twitter timeline style).

**Comment by zarino** [comment]
Initial response on this from @tmtmtmtm is good. Some points from our discussion:
- Maybe swap the pie charts for something that looks more like "this will/should change" like little speedometer-style dials? It should be clear that these figures will increase, and that _you_ can help increase them.
- Deffo thumbs up to some sort of message / call to action in the green section explaining what the completion figures mean and how ordinary people can contribute to the dataset (eg: via Gender Balance).
- Maybe distinguish 100% pie charts (less interesting) from partial pie charts (more interesting)? Maybe somehow suggest "these have been completed", "these are in progress", and "these are what we'll start collecting next"?

@chrismytton Could we talk early next week, about implementation of this?

**Comment by zarino** [comment]
Here's the latest thinking for the green bar at the top:

![everypolitician progress concept 3](https://cloud.githubusercontent.com/assets/739624/13146684/cfae4288-d64e-11e5-943f-04612faa92b0.png)

The circles are just stand-ins for some little charts. They should make it clear that the 100% ones have been completed (maybe a filled circle with a tick in the middle?), the in-progress ones are in progress (maybe a pie chart?), and the 0% ones haven't even been started (empty outlined circle?).

@tmtmtmtm suggested the fields we show could be customised on a per-country basis, and he could fix it so that there are only ever a multiple of 4 fields shown (so, if a country has 5 completed fields, and 4 in-progress, making a total of 9, the remaining 3 spaces will be manually filled up with future fields, to reach a nice square total of 12 items, split across three rows).

**Comment by zarino** [comment]
The [289-term-cards-concept](https://github.com/everypolitician/viewer-sinatra/tree/289-term-cards-concept) branch now looks like this:

![screen shot 2016-02-19 at 10 17 42](https://cloud.githubusercontent.com/assets/739624/13172851/3b993d6a-d6f2-11e5-89d7-be1f73980d3b.png)

@tmtmtmtm: Now you can see all that in place, do you want any more changes?

If not, there are still to backend things that someone else will need to do:
1. Pass the right statistics into the view (rather than the hard-coded stuff that's in there right now) – remember, there should be a multiple of 4 :-)
2. Progressively load the profile images as you scroll, rather than loading them all on pageload.

**Comment by tmtmtmtm** [comment]
That's starting to come together really well — thanks @zarino 

The main thought that this triggers now is that the 'Download as CSV' is no longer enough there, if lots of the fields we're going to include will only be in the JSON. So I think we need to change the 'download' part to be more flexible. We _could_ just do separate 'Download as CSV' and 'Download as JSON' like we had before, but I'm wondering if there's something better we could do? 

I'm also a little concerned that we're doing two conceptually different things in one go here, especially as those will probably end up being split between @chrismytton and I, and I'm not sure we need to wait until both are done before putting anything live. Are there dependencies in the design elements here or can we easily split the 'people as cards' and 'what's in the dataset' into two separate PRs?

**Comment by zarino** [comment]
@tmtmtmtm – I've broken the discussion about CSV/JSON downloads into this ticket, since I think it can be easily handled separately: https://github.com/everypolitician/everypolitician/issues/324

And you're right, the [289-term-cards-concept](https://github.com/everypolitician/viewer-sinatra/tree/289-term-cards-concept) branch can easily be split into two self-contained feature branches: Everything for the green statistics banner is in its own single commit – https://github.com/everypolitician/viewer-sinatra/commit/60e93d836ede2abbc2c6b409950552d29ddbe240. @chrismytton should be able to easily pull that out if he wants to work on that separately.

**Comment by tmtmtmtm** [comment]
@zarino can you re-push your copy of the `289-term-cards-concept` branch? I accidentally deleted the branch in a big clean-up this morning, and as there was no PR for it, I don't think there's any way to get it back (another reason why WIP PRs are always good!)

**Comment by tmtmtmtm** [comment]
From the commits I know were in it, I've reconstituted https://github.com/everypolitician/viewer-sinatra/tree/289-term-cards-concept-reconstructed, from which I've made a PR at https://github.com/everypolitician/viewer-sinatra/pull/4220, but I don't know whether this is complete.

**Comment by zarino** [comment]
@tmtmtmtm – no problem, I've pushed my copy of the branch to the newly named [`289-term-cards-concept-zz`](https://github.com/everypolitician/viewer-sinatra/tree/289-term-cards-concept-zz).

**Comment by tmtmtmtm** [comment]
Excellent — thanks @zarino 

I've opened a WIP PR for that at https://github.com/everypolitician/viewer-sinatra/pull/4254

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/viewer-sinatra/pull/4254
