### ISSUE TITLE
Tell Heroku apps to shut down when finished

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#449]
Now that we only have a fixed number of heroku hours available per month, we need to be more careful not to waste these. 

One potential quick win with services that only spin up to do a quick task, is to explicitly tell them to shut down again when finished, rather than leaving it for Heroku to time them out after half an hour.

**Comment by chrismytton** [comment]
# Short term fixes
- [x] Update internal apps in webhook-manager so that they only use the web hooks they need and aren’t woken up unnecessarily
- [ ] ~~Put dynos to sleep after they've done their work~~ Turns out Heroku doesn't have an API for this
- [x] Switch off `pull_request_preview` for now (we don't use it often, might be better to turn this into a command that can be run as a one off, possibly just locally for now)
- [x] Switch countries_json_updater to use EveryPolitician web hooks so we have greater control over when that is triggered.
- [ ] Add a check to the summarizer that fails if `countries.json` hasn't been updated.
- [x] Move apps that act on a newly opened or updated pull request over to Travis
  - [x] Extract the core functionality of these apps as callable libraries
  - [x] Update the original app to use the library
  - [x] Add a Raketask to ep-data that calls these libraries on Travis to perform the work previously done on Heroku.

# Possible future fixes
- Transfer apps to our personal Heroku accounts
- Consolidate the various Sidekiq workers into a single worker process (this would mean putting all the worker code into one repo, which would then present us with the problem of queues building up)
- Move apps over to mySociety servers
- Batch up work so that e.g. all rebuilds for the day are done at 4am
- Speed up the rebuilder
- Reduce the amount of work that's being done

**Comment by tmtmtmtm** [comment]
@chrismytton I'm keen to close this, as I think we've done most of what we actually need (for now at least). Are there things here you think we should still do (and don't have Issues already for them)?

**Comment by chrismytton** [comment]
I think this is Done Enough for now so I'm happy to close it. If we need to do anything else in the future we can track that separately.
