### ISSUE TITLE
store earliest term date in legislature data

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/everypolitician#464]
# Problem

(formerly everypolitician/everypolitician-data#12796 which was the wrong repo)

We're already recording `latest_term`. It would be handy to have `earliest_term` too to be able to more easily see how our historic coverage is doing across legislatures without diving into specific term data.

(I've got a personal agenda here because of the bot blog, but it's something that would be generally useful.)
# Proposed Solution

Add `earliest_term` at same time we're adding `latest_term`.
# Acceptance Criteria

Every legislature has an earliest term (unless there is no known start-of-term date for the _earliest_ term... (potentially odd but feasible circumstance)).
# Not Required

—
# Prerequisites

None
# Related Issues

None
# Due Date

—
# Design?

No
# Text?

No
# Bloggable?

No.

**Comment by tmtmtmtm** [comment]
>  to be able to more easily see how our historic coverage is doing across legislatures without diving into specific term data.

Doesn't the [count](https://github.com/everypolitician/everypolitician-data/blob/288c8d789a87ded52ea0d4237238a38dc1ccecd6/data/Turkey/Assembly/unstable/stats.json#L11) already give you that?

**Comment by davewhiteland** [comment]
When I unleash a block of pre-1600s data for the English parliament's House of Commons your count heuristic will not give us that, no ;-) :-p  Gah maybe it will because it's not the same as the UK House of Commons. 

In the meantime I wrote a `bin` script that extracts the dates I wanted so my personal need for this no longer exists. But I think it's not unreasonable to provide both ends of our date range; it's very modernist of us to assume the most recent data is the most interesting end of the data.

**Comment by tmtmtmtm** [comment]
> it's very modernist of us to assume the most recent data is the most interesting end of the data.

We're not actually assuming anything here. We're simply supplying the data that people have actually needed and are actively using{1}. If there's a real live reason why you (or anyone else) actually needs to answer the question "when does the data start from?" (rather than "how much historic data do you have?" which we already answer), then I'll add it straightaway. But I'm wary of adding something just because it seems like something someone _might_ want.

---

{1} which we know because the 'people' here is us, and we need to compare this date with the date of the most recent election to look for legislatures where we're out of date.
