### ISSUE TITLE
Rollbar error: Northern Ireland (no term IDs)

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician#581]
https://rollbar.com/everypolitician/rebuilder/items/1104/

The term 5 data is mostly coming in with no term information now.

**Comment by tmtmtmtm** [comment]
@chrismytton you want to try tracking this one down?

**Comment by chrismytton** [comment]
This was because the parlparse `people.json` was missing an `end_date` on memberships for term 5.

@dracos added the missing dates in https://github.com/mysociety/parlparse/commit/a306d4b5f5e3dc81f2c5f53c12078c53381ccf29 and https://github.com/everypolitician/everypolitician-data/pull/25940 has just appeared in the pull request queue.
