### ISSUE TITLE
Change Wikidata redirect IDs

### ISSUE THREAD

**Issue by generalist** [everypolitician/everypolitician#619]
# Problem

Wikidata items in the database are stored as the original Q-ID value, even when target items are merged - eg in the Bangladesh 9th & 10th parliaments, Muhammad Nazrul Islam is stored as Q26924778, but this item was recently merged into Q16345653 during a deduplication cleanup, and the old ID now redirects there.

Not all tools play nicely with redirected IDs and so it would be good to ensure that the "primary" ID is reflected in the downloads.

# Proposed Solution

Run a periodic script to check Wikidata IDs to see if they are redirects, and if so change the ID to the redirect (or produce a report for human confirmation). This would also allow for confirmation that the IDs still exist and have not been deleted for some reason (though perhaps something already does that?)

**Comment by tmtmtmtm** [comment]
@generalist this already largely happens, albeit not in a particularly automated manner. If you look at, for example, https://github.com/everypolitician/everypolitician-data/pull/61538, you'll see that Q26924778 is flagged up in the bot summary as no longer existing in the upstream data. At that point a human (usually me), re-reconciles to the new ID (in a case of a move), or finds out why that data is no longer appearing from Wikidata (sometimes it's due to on overzealous delete; sometimes vandalism of the P39 or other data; etc)

It would definitely be good if the redirects could be handled more automatically, but the current approach means the data is usually only stale for a few days (unless we've a large backlog to workthrough, like at present, when I've been travelling pretty much non-stop for the last few weeks)

**Comment by generalist** [comment]
Apologies, I hadn't realised this was already in your reports - I should have guessed that everything would be backed up a little at the moment!

This looks great - thanks.
